---
- name: Install Firewalld and Python Firewall Bindings
  become: yes
  dnf:
    name:
      - firewalld
      - python3-firewall
    state: present
    update_cache: yes

- name: Enable and Start Firewalld
  become: yes
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Ensure Firewalld Default Zone is Set
  become: yes
  shell: firewall-cmd --get-default-zone || firewall-cmd --set-default-zone=public
