---
- name: Install Java 17 (Jenkins agent dependency)
  become: yes #Ensure admin privileges
  dnf:
    name: java-17-openjdk-devel
    state: present # Ensures updates
    update_cache: yes

- name: Create Jenkins User
  become: yes
  user:
    name: jenkins
    shell: /bin/bash
    create_home: true
    home: /home/jenkins
