---
- name: Copy Gunicorn Service File
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  notify: Restart Gunicorn

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Nginx config for {{ domain }}
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ domain }}

- name: Enable Nginx site for {{ domain }}
  file:
    src: /etc/nginx/sites-available/{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ domain }}
    state: link

- name: Allow UFW for SSH and Web Ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443
    - 5000

- name: Enable the firewall
  ufw:
    state: enabled
    policy: allow

- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  register: cert

- name: Obtain SSL certificate with Certbot for {{ domain }}
  command: >
    certbot --nginx --non-interactive --agree-tos --redirect
    --email {{ certbot_email }}
    -d {{ domain }} -d www.{{ domain }}
  when: not cert.stat.exists
  register: certbot_result
  changed_when: "'Congratulations' in certbot_result.stdout"

- name: Ensure MongoDB config file exists
  stat:
    path: /etc/mongod.conf
  register: mongodb_conf

- name: Configure MongoDB to allow remote connections
  become: yes
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^  bindIp: 127\.0\.0\.1'
    line: '  bindIp: 0.0.0.0'
    backrefs: yes
  when: mongodb_conf.stat.exists  # Only run if file exists
  notify: restart mongodb